version: '3'
services:
  flaskblog:
    image: da0o/flaskblog
    restart: "always"
    ports:
      - "5000:5000"
  nginx:
    image: nginx:stable
    ports:
      - "80:80"
      - "443:443"
    restart: "always"
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "10"
    volumes:
      - /home/devops/flaskBlog/nginx.conf:/etc/nginx/nginx.conf
      - db:/python-docker/db
      - /etc/letsencrypt/:/etc/letsencrypt/

volumes:
  db:

